# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9c483368ac0fa4a9903b721d7e760737d6ff060d10df8dd395048d3ef8517266499701e80724f3497a055475bda153d6cca19b03b959aba121b50464bf5b396

test:
  secret_key_base: cf5ddbbc46b7bc726af1f08f18158cfd772f3a5c02353de96e1979e01fe094f9ebbdd3903806648ec2d7c59933d5722cffc96789209cc9b6e37a3d025a7de89a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
